using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using YamlDotNet.Core;
using YamlDotNet.RepresentationModel;
using static Skyline.Core.YamlTree;

namespace Skyline.Core;

/// <summary>Pure generation. The production catalog supplies embedded resources only.</summary>
public sealed class ConfigurationGenerator(ITemplateCatalog catalog)
{
    public GenerationResult Generate(ConfigurationInput input)
    {
        ArgumentNullException.ThrowIfNull(input);
        input = input with { Subscriptions = input.Subscriptions?.ToArray() ?? [] };
        var issues = InputValidator.Validate(input);
        if (issues.Any(i => i.Severity == IssueSeverity.Error)) return new(null, null, issues);
        var id = input.Target == ConfigurationTarget.Desktop ? "desktop" : "nas";
        try
        {
            var assembly = typeof(ConfigurationGenerator).Assembly;
            var version = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
            if (catalog.SoftwareVersion != version) throw new ConfigurationException(IssueCode.TemplateUnavailable);
            var template = catalog.Templates.SingleOrDefault(t => t.Id == id)
                ?? throw new ConfigurationException(IssueCode.ContractMismatch);
            var bytes = catalog.ReadTemplate(id);
            if (!Convert.ToHexString(SHA256.HashData(bytes)).Equals(template.Sha256, StringComparison.OrdinalIgnoreCase))
                throw new ConfigurationException(IssueCode.TemplateUnavailable);
            var source = new UTF8Encoding(false, true).GetString(bytes);
            var root = Parse(source);
            TemplateContractValidator.Validate(root, template);
            Apply(root, template, input);
            ConfigurationValidator.Validate(root);
            CheckPlaceholders(root, template, input);
            VerifyChanges(Parse(source), root, template, input);
            var body = Write(root);
            var roundTrip = Parse(body);
            if (!Equal(root, roundTrip)) throw new ConfigurationException(IssueCode.RoundTripMismatch);
            VerifyInputValues(roundTrip, template, input);
            var revision = assembly.GetCustomAttributes<AssemblyMetadataAttribute>().Single(a => a.Key == "BuildRevision").Value ?? "uncommitted";
            if (revision.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '-')) revision = "uncommitted";
            var yaml = $"# Generated by Skyline Configurator {version}\n# Template: {id} {template.Version}\n# Build revision: {revision}\n" + body;
            return new(yaml, id, issues, Changes(input));
        }
        catch (TemplateCatalogException) { issues.Add(new(IssueCode.TemplateUnavailable, "template")); }
        catch (ConfigurationException error) { issues.Add(new(error.Code, "template")); }
        catch (YamlException) { issues.Add(new(IssueCode.InvalidYaml, "template")); }
        catch (DecoderFallbackException) { issues.Add(new(IssueCode.InvalidYaml, "template")); }
        return new(null, id, issues);
    }

    private static HashSet<string> Enabled(ConfigurationInput input) => input.Subscriptions.Where(s => s.Enabled)
        .Select(s => $"my-subscription-{s.Slot}").ToHashSet(StringComparer.Ordinal);
    private static void Apply(YamlMappingNode root, TemplateDescriptor template, ConfigurationInput input)
    {
        var residential = Named(root, "proxies", template.ResidentialProxyName);
        Set(residential, "server", Text(input.Server!.Trim()));
        Set(residential, "port", Integer(int.Parse(input.Port!, CultureInfo.InvariantCulture)));
        Set(residential, "username", Text(input.Username!));
        Set(residential, "password", Text(input.Password!));
        var providers = Map(Get(root, "proxy-providers"));
        var enabled = Enabled(input);
        foreach (var slot in template.SubscriptionSlots.Where(s => !enabled.Contains(s))) Remove(providers, slot);
        foreach (var sub in input.Subscriptions.Where(s => s.Enabled))
            Set(Map(Get(providers, $"my-subscription-{sub.Slot}")), "url", Text(sub.Url!));
        FilterUses(root, template.SubscriptionSlots.Where(s => !enabled.Contains(s)).ToHashSet(StringComparer.Ordinal));
        Set(Map(Get(Map(Get(root, "dns")), "nameserver-policy")), "geosite:private", new YamlSequenceNode(Text(input.LocalDns!)));
        Set(root, "secret", Text(input.ControllerSecret!));
        if (input.Target == ConfigurationTarget.Nas) Set(root, "authentication", new YamlSequenceNode(Text(input.NasUsername + ":" + input.NasPassword)));
    }

    private static void FilterUses(YamlMappingNode root, HashSet<string> removed)
    {
        foreach (var group in Maps(root, "proxy-groups").Where(g => Has(g, "use")))
        {
            var sequence = Seq(Get(group, "use"));
            for (var i = sequence.Children.Count - 1; i >= 0; i--)
                if (removed.Contains(Str(sequence.Children[i]))) sequence.Children.RemoveAt(i);
        }
    }

    internal static void VerifyChanges(YamlMappingNode before, YamlMappingNode after, TemplateDescriptor template, ConfigurationInput input)
    {
        // Projection removes ONLY authorized leaf edits; provider settings and list order remain compared.
        var enabled = Enabled(input);
        var providersAfter = Map(Get(after, "proxy-providers"));
        if (!providersAfter.Children.Keys.Select(Str).ToHashSet(StringComparer.Ordinal).SetEquals(enabled))
            throw new ConfigurationException(IssueCode.UnexpectedChange);
        var projectedAfter = Parse(Write(after));
        var removed = template.SubscriptionSlots.Where(s => !enabled.Contains(s)).ToHashSet(StringComparer.Ordinal);
        foreach (var slot in removed) Remove(Map(Get(before, "proxy-providers")), slot);
        FilterUses(before, removed);
        foreach (var tree in new[] { before, projectedAfter })
        {
            var residential = Named(tree, "proxies", template.ResidentialProxyName);
            foreach (var key in new[] { "server", "port", "username", "password" }) Remove(residential, key);
            foreach (var slot in enabled) Remove(Map(Get(Map(Get(tree, "proxy-providers")), slot)), "url");
            Remove(Map(Get(Map(Get(tree, "dns")), "nameserver-policy")), "geosite:private");
            Remove(tree, "secret");
            if (input.Target == ConfigurationTarget.Nas) Remove(tree, "authentication");
        }
        if (!Equal(before, projectedAfter)) throw new ConfigurationException(IssueCode.UnexpectedChange);
    }

    private static void VerifyInputValues(YamlMappingNode root, TemplateDescriptor template, ConfigurationInput input)
    {
        void Same(YamlNode node, string value)
        {
            if (node is not YamlScalarNode s || s.Value != value || Kind(s) != "string")
                throw new ConfigurationException(IssueCode.RoundTripMismatch);
        }
        var residential = Named(root, "proxies", template.ResidentialProxyName);
        Same(Get(residential, "server"), input.Server!.Trim());
        Same(Get(residential, "username"), input.Username!);
        Same(Get(residential, "password"), input.Password!);
        Same(Get(root, "secret"), input.ControllerSecret!);
        Same(Seq(Get(Map(Get(Map(Get(root, "dns")), "nameserver-policy")), "geosite:private")).Children.Single(), input.LocalDns!);
        if (input.Target == ConfigurationTarget.Nas) Same(Seq(Get(root, "authentication")).Children.Single(), input.NasUsername + ":" + input.NasPassword);
        foreach (var sub in input.Subscriptions.Where(s => s.Enabled))
            Same(Get(Map(Get(Map(Get(root, "proxy-providers")), $"my-subscription-{sub.Slot}")), "url"), sub.Url!);
        var port = Get(residential, "port");
        if (port is not YamlScalarNode scalar || Kind(scalar) != "number" || scalar.Value != int.Parse(input.Port!, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture))
            throw new ConfigurationException(IssueCode.RoundTripMismatch);
    }

    private static void CheckPlaceholders(YamlMappingNode root, TemplateDescriptor template, ConfigurationInput input)
    {
        var residential = Named(root, "proxies", template.ResidentialProxyName);
        if (Str(residential, "server") == "socks5.example.com" || Str(residential, "username") == "YOUR_SOCKS5_USERNAME"
            || Str(residential, "password") == "YOUR_SOCKS5_PASSWORD"
            || Str(root, "secret") is "your_secret_here" or "CHANGE_ME_CONTROLLER_SECRET")
            throw new ConfigurationException(IssueCode.Placeholder);
        if (input.Target == ConfigurationTarget.Nas && (input.NasUsername == "CHANGE_ME_PROXY_USER" || input.NasPassword == "CHANGE_ME_PROXY_PASSWORD"))
            throw new ConfigurationException(IssueCode.Placeholder);
        foreach (var provider in Map(Get(root, "proxy-providers")).Children.Values.Select(Map))
            if (Enumerable.Range(1, 6).Any(i => Str(provider, "url").Contains($"YOUR_SUBSCRIPTION_TOKEN_{i}", StringComparison.Ordinal)))
                throw new ConfigurationException(IssueCode.Placeholder);
    }

    private static IEnumerable<ConfigurationChange> Changes(ConfigurationInput input)
    {
        foreach (var field in new[] { "server", "port", "username", "password", "localDns", "controllerSecret" }) yield return new("Updated", field);
        for (var slot = 1; slot <= 6; slot++) yield return new(input.Subscriptions.Any(s => s.Slot == slot && s.Enabled) ? "Enabled" : "Removed", "subscriptions", slot);
        if (input.Target == ConfigurationTarget.Nas) yield return new("Updated", "nasAuthentication");
    }
}
